enableWebServer: true
webServerPort: 8080
minecraftServerHostname: change.me.com
serverName: JukeBukkit
allowWebServerUploads: true
allowExternalURLs: true
texturePack: default
debug: false

